language: node_js
node_js:
  - 12

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker tag udagram-api-feed anhntc20011997/udagram-api-feed:v5
  - docker build -t udagram-api-user ./udagram-api-user
  - docker tag udagram-api-user anhntc20011997/udagram-api-user:v5
  - docker build -t udagram-frontend ./udagram-frontend
  - docker tag udagram-frontend anhntc20011997/udagram-frontend:v5
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy
  - docker tag udagram-reverseproxy anhntc20011997/udagram-reverseproxy:v5

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push anhntc20011997/udagram-api-feed:v5
  - docker push anhntc20011997/udagram-api-user:v5
  - docker push anhntc20011997/udagram-frontend:v5
  - docker push anhntc20011997/udagram-reverseproxy:v5

# commit 
